$(function() {
    // setting varable

    /*
    Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
    http://darkskyapp.github.io/skycons/
    */
    var skycons = new Skycons();

    // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
    // skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
    // skycons.add("day1", Skycons.CLEAR_DAY);
    // skycons.add("day2", Skycons.CLOUDY);
    // skycons.add("day3", Skycons.RAIN);

    // start all icons animation!
    skycons.play();

    // update a icon on  canvas by its id
    // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);



    var date = $('.date'),
        temp = $('.temperature'),
        condition = $('.condition'),
        btn = $('button');


    var url,
        citys = [],
        citys_en = [],
        month = [];

    var addskycons = function(text) {
        switch (text) {
            case "Breezy":
                return Skycons.WIND
                break;

            case "Scattered Thunderstorms":
                return Skycons.CLOUDY
                break;

            case "Rain":
                return Skycons.RAIN
                break;

            case "Scattered Showers":
                return Skycons.RAIN
                break;

            case "Sunny":
                return Skycons.CLEAR_DAY
                break;

            case "Cloudy":
                return Skycons.CLOUDY
                break;

            case "Partly Cloudy":
                return Skycons.PARTLY_CLOUDY_DAY
                break;

            case "Mostly Cloudy":
                return Skycons.CLOUDY
                break;

            case "Rain And Snow":
                return Skycons.SLEET
                break;

            case "Thunderstorms":
                return Skycons.CLOUDY
                break;

            case "Mostly Sunny":
                return Skycons.CLEAR_DAY
                break;

            case "Showers":
                return Skycons.RAIN
                break;

            default:
                return null;
        }
    }
    
    citys = ["臺北市", "新北市", "台中市", "臺南市", "高雄市", "基隆市", "桃園市", "新竹市", "新竹縣", "苗栗縣", "彰化縣", "南投縣", "雲林縣", "嘉義市", "嘉義縣", "屏東縣", "宜蘭縣", "花蓮縣", "台東縣", "澎湖縣", "金門縣", "連江縣"];
    citys_en = ["Taibei City", "New Taipei City  ", "Taichung City", "Tainan City ", "Kaohsiung City", "Keelung City", "Taoyuan City", "Hsinchu City", "Hsinchu County", "Miaoli County", "Changhua County", "Nantou County", "Yunlin County", "Chiayi City", "Chiayi County", "Pingtung County", "Yilan County ", "Hualien County", "Taitung County", "Penghu County", "Kinmen County", "Lienchiang "];
    month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    $.getWeatherJSON = function(url, callback) {
        $.getJSON(url, function(data) {
            if (data && data.query && data.query.results) { // if data.query.results exist , do the following action.
                callback(data)
            } else {
                console.info("reloading : ", url)
                $.getWetaherJson(url, callback)
            }
        })
    }

    // jquery start


    url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taibei City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"

    // get the data of the city
    $.getWeatherJSON(url, function(data) {
        // check location
        // alert(JSON.stringify(data.query.results.channel.location)); 

        var currentTemperatureText = Math.round((data.query.results.channel.item.condition.temp - 32) * 5 / 9),
            currentdate = new Date(data.query.results.channel.item.forecast[0].date),
            text = data.query.results.channel.item.condition.text;
        var forecast1 = data.query.results.channel.item.forecast[1];

        var forecast2 = data.query.results.channel.item.forecast[2];

        var forecast3 = data.query.results.channel.item.forecast[3];



        // today
        currentdate = currentdate.getDate() + " " + month[currentdate.getMonth()] + " " + currentdate.getFullYear();
        condition.html('<span class="date">' + currentdate + '</span>: ' + text)
        temp.text(currentTemperatureText);
        skycons.set("today", addskycons(text));

        // forecast1
        $('.date_tr :nth-child(1)').text(forecast1.date);
        $('.temp_tr :nth-child(1)').html(Math.round((forecast1.low - 32) * 5 / 9) + "-" + Math.round((forecast1.high - 32) * 5 / 9) + " &#8451;");
        skycons.set("day1", addskycons(forecast1.text));

        // forecast2

        $('.date_tr :nth-child(2)').text(forecast2.date);
        $('.temp_tr :nth-child(2)').html(Math.round((forecast2.low - 32) * 5 / 9) + "-" + Math.round((forecast2.high - 32) * 5 / 9) + " &#8451;");
        skycons.set("day2", addskycons(forecast2.text));
        // forecast3

        $('.date_tr :nth-child(3)').text(forecast3.date);
        $('.temp_tr :nth-child(3)').html(Math.round((forecast3.low - 32) * 5 / 9) + "-" + Math.round((forecast3.high - 32) * 5 / 9) + " &#8451;");
        skycons.set("day3", addskycons(forecast3.text));
    })








    // for dropdown list

    $.each(citys_en, function(index, value) {
        url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + value + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"


        $.getWeatherJSON(url, function(data) {

            // get current temperatuer for the dropdown button
            var currentTemperature = data.query.results.channel.item.condition.temp;
            var currentTemperatureText = Math.round((currentTemperature - 32) * 5 / 9) + "&#8451";

            $('#' + index).append('<span>' + currentTemperatureText + '</span>');

        })

        $('#dropdown').append('<li role="presentation"  ><a role="menuitem" tabindex="-1" href="#" id="' + index + '" >' + citys[index] + '</a></li>');

    })

    // click the button

    $('#dropdown li').on('click', function() {

        var id = $(this).children().attr('id');
        url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + citys_en[id] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"

        // get the data of the city
        $.getWeatherJSON(url, function(data) {
            // check location
               console.log(JSON.stringify(data.query.results.channel.location)); 

            var currentTemperatureText = Math.round((data.query.results.channel.item.condition.temp - 32) * 5 / 9),
                currentdate = new Date(data.query.results.channel.item.forecast[0].date),
                text = data.query.results.channel.item.condition.text;
            var forecast1 = data.query.results.channel.item.forecast[1];

            var forecast2 = data.query.results.channel.item.forecast[2];

            var forecast3 = data.query.results.channel.item.forecast[3];



            // today
            currentdate = currentdate.getDate() + " " + month[currentdate.getMonth()] + " " + currentdate.getFullYear();
            condition.html('<span class="date">' + currentdate + '</span>: ' + text)
            temp.text(currentTemperatureText);
            skycons.set("today", addskycons(text));

            // forecast1
            $('.date_tr :nth-child(1)').text(forecast1.date);
            $('.temp_tr :nth-child(1)').html(Math.round((forecast1.low - 32) * 5 / 9) + "-" + Math.round((forecast1.high - 32) * 5 / 9) + " &#8451;");
            skycons.set("day1", addskycons(forecast1.text));

            // forecast2

            $('.date_tr :nth-child(2)').text(forecast2.date);
            $('.temp_tr :nth-child(2)').html(Math.round((forecast2.low - 32) * 5 / 9) + "-" + Math.round((forecast2.high - 32) * 5 / 9) + " &#8451;");
            skycons.set("day2", addskycons(forecast2.text));
            // forecast3

            $('.date_tr :nth-child(3)').text(forecast3.date);
            $('.temp_tr :nth-child(3)').html(Math.round((forecast3.low - 32) * 5 / 9) + "-" + Math.round((forecast3.high - 32) * 5 / 9) + " &#8451;");
            skycons.set("day3", addskycons(forecast3.text));
        })


        btn.text($(this).text());
        btn.append('<span class="caret"></span>');

    });
}())
